FROM maven:3-jdk-8-slim
# ----
# Install project dependencies and keep sources
# make source folder
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
# install maven dependency packages (keep in image)
COPY pom.xml /usr/src/app
COPY src /usr/src/app/src

#RUN mvn -T 1C install && rm -rf target
RUN mvn clean install


# Base Alpine Linux based image with OpenJDK JRE only
FROM openjdk:8-jre-alpine
# copy application WAR (with libraries inside)
# copy other source files (keep in image)
COPY --from=0 /usr/src/app/target/*.jar /run

#CMD ["mvn", "clean install"]
#COPY target/*.jar /run
# specify default command'
#CMD ["/target", "ls"]
CMD ["/usr/bin/java", "-jar", "-Dspring.profiles.active=default-docker", "/run/recipe-service-0.0.1-SNAPSHOT.jar"]