package com.lemparty.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import org.springframework.data.annotation.Id;

import java.io.Serializable;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@DynamoDBTable(tableName = "recipes")
public class Recipe implements Serializable {

    @DynamoDBHashKey
    public String recipeID;

    @DynamoDBIndexHashKey(globalSecondaryIndexName="dateUserIndex")
    private String userID;
    private String userFirstName;
    private String userLastName;

    @DynamoDBAttribute
    private String name;
    private String cuisine;
    private String description;
    private String note;

    @DynamoDBAttribute
    private Date date;

    @DynamoDBIndexRangeKey(globalSecondaryIndexName="dateUserIndex")
    private long datestring;

    public long getDatestring() {
        return datestring;
    }

    public void setDatestring(long datestring) {
        this.datestring = datestring;
    }

    public Date getDate() {
        //return this.recipeID.getDate();
        return this.date;
    }

    public void setDate(Date date) {
//        if (this.recipeID == null) {
//            this.recipeID = new RecipeID();
//        }
//        this.recipeID.setDate(date);
        this.date = date;
    }

    public String getUserFirstName() {
        return userFirstName;
    }

    public void setUserFirstName(String userFirstName) {
        this.userFirstName = userFirstName;
    }

    public String getUserLastName() {
        return userLastName;
    }

    public void setUserLastName(String userLastName) {
        this.userLastName = userLastName;
    }

    private List<Ingredient> ingredientsList = new ArrayList<Ingredient>();

    @Id
    public String getRecipeID() {
       // return this.recipeID.getRecipeID();
        return this.recipeID;
    }

    public void setRecipeID(String recipeID) {
        this.recipeID = recipeID;
//        if (this.recipeID == null) {
//            this.recipeID = new RecipeID();
//        }
//        this.recipeID.setRecipeID(recipeID);
    }

    public String getUserID() {
        return userID;
    }

    public void setUserID(String userID) {
        this.userID = userID;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCuisine() {
        return cuisine;
    }

    public void setCuisine(String cuisine) {
        this.cuisine = cuisine;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public List<Ingredient> getIngredientsList() {
        return ingredientsList;
    }

    public void setIngredientsList(List<Ingredient> ingredientsList) {
        this.ingredientsList = ingredientsList;
    }


//    public class RecipeID implements Serializable{
//        @DynamoDBHashKey
//        @DynamoDBAutoGeneratedKey
//        private String recipeID;
//
//        @DynamoDBRangeKey
//        private Date date;
//
//        public String getRecipeID() {
//            return recipeID;
//        }
//
//        public void setRecipeID(String recipeID) {
//            this.recipeID = recipeID;
//        }
//
//        public Date getDate() {
//            return date;
//        }
//
//        public void setDate(Date date) {
//            this.date = date;
//        }
//    }
}
